dof-dss/Unity_svr_2

project/config/ircommission/block.block.views_block__irc_key_documents_views_block_key_docs_homepage.yml, project/config/ircommission/core.extension.yml, project/config/ircommission/views.view.irc_key_documents_views.yml, project/sites/ircommission/themes/ircommission_theme/css/components.css, project/sites/ircommission/themes/ircommission_theme/src/scss/components.scss
Updated Key Docs block names and css
=> Updated Key Docs block names and css

config/ircommission/local/.htaccess, config/ircommission/local/dblog.settings.yml, config/ircommission/local/ultimate_cron.job.dblog_cron.yml, config/ircommission/local/views.view.watchdog.yml, project/config/ircommission/ircommission_theme.settings.yml
Ircommission Logo location update.
Use logo supplied by theme
=> Logo location update

project/config/ircommission/config/structure_sync.data.yml
Added Structure sync for About IRC block
Committing structure_sync.data.yml
=> Added Structure sync for About IRC block

project/sites/ircommission/themes/ircommission_theme/templates/block/block--ircommission-theme-aboutircblock.html.twig
Updated banner, removed whitespace
=> Updated banner, removed whitespace

project/config/ircommission/config/core.extension.yml, project/config/ircommission/config/system.action.user_add_role_action.qa.yml, project/config/ircommission/config/system.action.user_remove_role_action.qa.yml, project/config/ircommission/config/user.role.qa.yml
=> Added QA module

project/config/ircommission/config/config_split.config_split.local.yml, project/config/ircommission/config/core.entity_form_display.node.publication_page.default.yml, project/config/ircommission/config/core.entity_view_display.node.publication_page.default.yml, project/config/ircommission/config/core.entity_view_display.node.publication_page.teaser.yml, project/config/ircommission/config/core.extension.yml, project/config/ircommission/config/field.field.node.publication_page.field_attachment.yml, project/config/ircommission/config/field.storage.node.field_attachment.yml, project/sites/ircommission/modules/custom/ircommission_migrations/config/install/migrate_plus.migration.upgrade_d7_file_document.yml, project/sites/ircommission/modules/custom/ircommission_migrations/config/install/migrate_plus.migration.upgrade_d7_node_complete_publication_page.yml
=> Publication changes

project/config/ircommission/config/system.site.yml
=> Sitename typo corrected

config/ircommission/local/.htaccess, project/config/ircommission/config/flag.flag.disable_toc.yml, project/config/ircommission/config/language.content_settings.node.page.yml, project/config/ircommission/config/node.type.page.yml
=> added Table of Contents

project/config/ircommission/config/block.block.breadcrumbs.yml, project/config/ircommission/config/block.block.views_block__irc_key_documents_views_block_2.yml, project/config/ircommission/config/core.extension.yml, project/config/ircommission/config/facets.facet_source.search_api__views_page__publications_search__publication_search_page.yml
=> Updated breadcrumbs

project/config/ircommission/config/node.type.featured_content_list.yml, project/config/ircommission/config/node.type.news.yml, project/config/ircommission/config/node.type.page.yml
=> Updated menu settings

project/config/ircommission/config/views.view.publications_search.yml
Edit on publications search page, added text: Published
=> D8UN-1314-b

project/config/ircommission/config/views.view.publications_search.yml
Added colon on publications search
=> D8UN-1314-c

project/sites/hiaredressni/themes/hiaredressni_theme/templates/block/block--footerlinks.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/block/block--system-branding-block.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/block/block--system-main-block.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/block/block--views-exposed-filter-block.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/content/node--search-index.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--field-teaser.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-next-audit-due--diff.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-publication-type--diff.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-published-date--search-index.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-published-date.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-teaser--diff.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/layout/page.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/views/views-view--publication-search-page.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/views/views-view--search-page.html.twig, project/sites/hiaredressni/themes/hiaredressni_theme/templates/views/views-view-unformatted--search-result-page.html.twig
=> Twig updates 

project/config/hiaredressni/config/block.block.breadcrumbs.yml, project/config/hiaredressni/config/block.block.footermenu.yml, project/config/hiaredressni/config/block.block.mainpagecontent.yml, project/config/hiaredressni/config/block.block.pagetitle.yml, project/config/hiaredressni/config/block.block.sidemenu.yml
=> block configs

project/sites/hiaredressni/themes/hiaredressni_theme/templates/field/field--node--field-published-date--full.html.twig
updated publications date field
=> updated publications date field

project/config/hiaredressni/config/block.block.guidanceforapplicants.yml, project/config/hiaredressni/config/block.block.hiaredress_theme_system_main.yml, project/config/hiaredressni/config/block.block.keydocuments.yml, project/config/hiaredressni/config/block.block.legaladviceandsupport.yml, project/config/hiaredressni/config/block.block.makeanapplication.yml, project/sites/hiaredressni/themes/hiaredressni_theme/hiaredressni_theme.info.yml
updating custom blocks and regions
=> updating custom blocks and regions

project/sites/hiaredressni/themes/hiaredressni_theme/templates/layout/page.html.twig
=> fixed fourth top region

project/config/hiaredressni/config/block.block.footerlinks.yml
=> added cookies

project/config/hiaredressni/config/block.block.footerlinks.yml, project/config/hiaredressni/config/structure_sync.data.yml
updating list of links / structure sync
=> updating list of links / structure sync

project/config/hiaredressni/config/block.block.sitesearchblock.yml, project/config/hiaredressni/config/core.extension.yml, project/config/hiaredressni/config/views.view.search.yml
=> added Unity site search

project/config/hiaredressni/config/core.entity_form_display.node.faq.default.yml, project/config/hiaredressni/config/core.entity_view_display.node.faq.default.yml, project/config/hiaredressni/config/core.entity_view_display.node.faq.teaser.yml, project/config/hiaredressni/config/field.field.node.faq.field_faq.yml, project/config/hiaredressni/config/field.storage.node.field_faq.yml, project/config/hiaredressni/config/node.type.faq.yml
=> hia faqs config setup

project/config/ircommission/config/workflows.workflow.nics_editorial_workflow.yml
=> updated workflow

cronjob.sh, project/config/ircommission/config/core.extension.yml, project/config/ircommission/config/filelog.settings.yml, project/config/ircommission/config/ultimate_cron.job.filelog_cron.yml
Added logging for ircommission
=> D8 un 1470

cronjob.sh, project/config/hiaredressni/config/core.extension.yml, project/config/hiaredressni/config/filelog.settings.yml, project/config/hiaredressni/config/ultimate_cron.job.filelog_cron.yml
=> Hia logging

project/config/hiaredressni/config/core.entity_form_display.node.publication.default.yml
removed summary and photo attachment
=> removed summary and photo attachment

.circleci/config.yml
Pull in latest changes from unity_base
=> Git pull upstream main

project/config/hiaredressni/config/eu_cookie_compliance.settings.yml, project/config/hiaredressni/config/user.role.anonymous.yml, project/config/hiaredressni/config/user.role.authenticated.yml, project/config/hiaredressni/config/user.role.author_user.yml, project/config/hiaredressni/config/user.role.supervisor_user.yml
Updated Permissions and cookie banner
=> Updated Permissions and cookie banner

project/config/hiaredressni/config/core.extension.yml
=> Installed Unity breadcrumbs

project/config/src/config/block.block.breadcrumbs.yml
=> removed breadcrumb title

project/config/src/config/block.block.exposedformpublications_searchpublication_search_page.yml, project/config/src/config/block.block.sitesearchblock.yml, project/config/src/config/views.view.search.yml, project/sites/src/themes/src_theme/templates/field/field--node--field-publication-date--full.html.twig
search view,date twig, blocks placed
=> search view,date twig, blocks placed

project/config/src/config/user.role.anonymous.yml, project/config/src/config/user.role.authenticated.yml, project/config/src/config/user.role.author_user.yml, project/config/src/config/user.role.supervisor_user.yml
=> Updated permissions

project/config/src/config/editor.editor.basic_html.yml
=> enabled Linkit on SRC

project/sites/ircommission/themes/ircommission_theme/templates/layout/page.html.twig
=> updated irc page twig

project/config/hiaredressni/config/config_split.config_split.production.yml, project/config/hiaredressni/production/fastly.settings.yml
Added Fastly to Production config split
=> Added Fastly to config split

project/config/sentencereview/config/node.type.publication.yml
Removed menu settings from Publications content type
=> Removed menu settings

project/config/pacni/config/editor.editor.basic_html.yml, project/config/pacni/config/filter.format.basic_html.yml
=> enabled linkit basic_html

project/config/pacni/config/block.block.contactusblock.yml
=> pacni contact us block

project/config/pacni/config/block.block.views_block__latest_news_latest_news.yml, project/config/pacni/config/core.extension.yml, project/config/pacni/config/facets.facet.published_date.yml, project/config/pacni/config/facets_summary.facets_summary.news_summary.yml, project/config/pacni/config/views.view.news_search.yml
Pacni news facet/ view / placement
=> Pacni facets news

project/config/pacni/config/csp.settings.yml
=> disabled csp reporting

project/config/pacni/config/user.role.author_user.yml, project/config/pacni/config/user.role.supervisor_user.yml
user roles updated, redundant page content removed
=> user roles updated, redundant page content removed

project/config/pacni/config/block.block.footerlinks.yml
=> updated footer links

.platform/routes.yaml, project/config/victimspaymentsboard/config/google_tag.container.vpb.yml, project/config/victimspaymentsboard/config/system.performance.yml, project/config/victimspaymentsboard/config/system.site.yml, project/project.yml
Small changes after post launch checks
=> Vpb post launch

project/config/pacni/config/node.type.basic_page.yml
=> basic page toc update

project/config/pacni/config/core.entity_view_display.node.publication.diff.yml, project/config/pacni/config/core.entity_view_display.node.publication.search_index.yml
updated revision comparison on pacni
=> updated revision comparison

project/config/pacni/config/block.block.publisheddate_publications.yml, project/config/pacni/config/facets.facet_source.search_api__views_page__publications_search__publication_search_page.yml, project/config/pacni/config/search_api.index.publications.yml
=> added date facet

project/config/sentencereview/config/core.entity_view_display.node.publication.default.yml, project/config/sentencereview/config/core.entity_view_display.node.publication.diff.yml, project/config/sentencereview/config/editor.editor.basic_html.yml
Src post show tell fixes
Linkit enabled
Publication page displays fixes
=> Src post show tell fixes

project/config/sentencereview/config/config_split.config_split.local.yml
=> updated config split local

project/config/industrialcourt/config/config_split.config_split.local.yml
=> local split update Industrial

.platform/routes.yaml, project/config/ircommission/config/google_tag.container.irc_analytics.yml, project/config/ppsni/config/google_tag.container.ppsni_analytics.yml, project/config/ppsni/config/readonlymode.settings.yml, project/config/ppsni/config/system.performance.yml, project/config/ppsni/config/system.site.yml, project/project.yml
Post launch changes for IR Commission and PPSNI
=> Post launch irc ppsni

project/config/industrialcourt/config/config_split.config_split.local.yml, project/config/industrialcourt/config/core.extension.yml, project/config/industrialcourt/production/.htaccess
Industrial htaccess on production split
removed Migrate Drupal
=> Industrial htaccess

project/config/industrialcourt/config/block.block.sitesearchblock.yml, project/config/industrialcourt/config/views.view.search.yml, project/sites/industrialcourt/themes/industrialcourt_theme/templates/layout/page.html.twig
site search created/placed and template
=> site search created/placed and template

project/config/industrialcourt/config/user.role.anonymous.yml, project/config/industrialcourt/config/user.role.authenticated.yml, project/config/industrialcourt/config/user.role.author_user.yml, project/config/industrialcourt/config/user.role.supervisor_user.yml
=> permissions updated

project/config/industrialcourt/config/block.block.sitebranding.yml
=> activated slogan

project/sites/industrialcourt/modules/custom/industrialcourt_migrations/config/install/migrate_plus.migration.upgrade_d7_node_complete_decision.yml
=> updated decisions body field

project/config/industrialcourt/config/block.block.date.yml, project/config/industrialcourt/config/block.block.employername.yml, project/config/industrialcourt/config/block.block.exposedformdecision_searchdecision_search_page.yml, project/config/industrialcourt/config/block.block.exposedformpublications_searchpublication_search_page.yml, project/config/industrialcourt/config/block.block.type.yml, project/config/industrialcourt/config/block.block.union.yml
added publication_search_page
updated facet weights
=> added publication_search_page

project/config/industrialcourt/config/field.field.node.publication.field_publication_type.yml
=> field required enabled

project/config/industrialcourt/config/block.block.pagetitle.yml
=> updated page title block

project/config/interchangeni/config/config_split.config_split.local.yml, project/config/interchangeni/config/core.extension.yml
Uninstall some migrate modules when on hosted environment
=> Interchange NI config fixes

composer.json, composer.lock
pulling entityqueue patch to Unity 2
=> D8 un 2364 c

composer.lock
New version of maestro_hosting that fixes Solr problems
=> Upgrade maestro

composer.json, composer.lock, project/config/communityrelations/config/views.view.workflow_moderation.yml, project/config/cosicani/config/views.view.workflow_moderation.yml, project/config/cvocni/config/views.view.workflow_moderation.yml, project/config/hiaredressni/config/views.view.workflow_moderation.yml, project/config/imtac/config/views.view.workflow_moderation.yml, project/config/ircommission/config/views.view.workflow_moderation.yml, project/config/mentalhealthchampionni/config/views.view.workflow_moderation.yml, project/config/nicertoffice/config/views.view.workflow_moderation.yml, project/config/nicybersecuritycentre/config/views.view.workflow_moderation.yml, project/config/nijac/config/views.view.workflow_moderation.yml, project/config/ppsni/config/views.view.workflow_moderation.yml, project/config/publicappointmentsni/config/views.view.workflow_moderation.yml, project/config/sentencereview/config/views.view.workflow_moderation.yml, project/config/victimspaymentsboard/config/views.view.workflow_moderation.yml
Install latest origins modules and overwrite admin/content view for all sites
=> Update content view

project/config/sentencereview/config/editor.editor.basic_html.yml, project/config/sentencereview/config/editor.editor.full_html.yml, project/config/sentencereview/config/filter.format.basic_html.yml, project/config/sentencereview/config/filter.format.full_html.yml, project/config/sentencereview/config/system.site.yml
Add missing CKEditor 5 config to 'basic html' and 'full html' text formats.
Also change site homepage after node 1 was deleted in error.
=> D8UN-2663 Sentence Review CKEditor 5 config

.lando.base.yml
See github.com/dof-dss/nicsdru_unity/pull/1947 for details
=> Unity2: Shift front-end tooling out of appserver container into own

project/config/communityrelations/config/http_cache_control.settings.yml, project/config/communityrelations/config/system.performance.yml, project/config/cosicani/config/http_cache_control.settings.yml, project/config/cosicani/config/system.performance.yml, project/config/cvocni/config/http_cache_control.settings.yml, project/config/cvocni/config/system.performance.yml, project/config/hiaredressni/config/http_cache_control.settings.yml, project/config/hiaredressni/config/system.performance.yml, project/config/imtac/config/http_cache_control.settings.yml, project/config/imtac/config/system.performance.yml, project/config/ircommission/config/http_cache_control.settings.yml, project/config/ircommission/config/system.performance.yml, project/config/mentalhealthchampionni/config/http_cache_control.settings.yml, project/config/mentalhealthchampionni/config/system.performance.yml, project/config/nicertoffice/config/http_cache_control.settings.yml, project/config/nicertoffice/config/system.performance.yml, project/config/nicybersecuritycentre/config/http_cache_control.settings.yml, project/config/nicybersecuritycentre/config/system.performance.yml, project/config/nijac/config/http_cache_control.settings.yml, project/config/nijac/config/system.performance.yml, project/config/ppsni/config/http_cache_control.settings.yml, project/config/ppsni/config/system.performance.yml, project/config/publicappointmentsni/config/http_cache_control.settings.yml, project/config/publicappointmentsni/config/system.performance.yml, project/config/sentencereview/config/http_cache_control.settings.yml, project/config/sentencereview/config/system.performance.yml, project/config/victimspaymentsboard/config/http_cache_control.settings.yml, project/config/victimspaymentsboard/config/system.performance.yml
Updating the Browser Cache setting from 5 minutes to 15 minutes on all of the Unity 2 sites.
=> D8UN-2701 U2

.circleci/config.yml, composer.json, composer.lock
Apply core patch to fix menu revision langcode error
=> D8UN-2712 Parent menu link bug fix

project/config/cvocni/config/language.content_settings.taxonomy_term.crime_types.yml, project/config/cvocni/config/taxonomy.vocabulary.crime_types.yml
- Exporting UUID for taxonomy vocab from production to avoid edge fail.
=> Taxonomy clash fix

composer.json, composer.lock
- Upgrade google_tag module in preparation for Google consent mode
- Pull other upstream changes
=> Google consent mode

composer.lock, project/config/cvocni/config/webform.webform.feedback_form.yml
- Consent question added to bottom of CVOCNI feedback form
=> Tweak to CVOCNI webform

project/config/communityrelations/config/system.performance.yml, project/config/cosicani/config/system.performance.yml, project/config/cvocni/config/system.performance.yml, project/config/hiaredressni/config/system.performance.yml, project/config/imtac/config/system.performance.yml, project/config/ircommission/config/system.performance.yml, project/config/mentalhealthchampionni/config/system.performance.yml, project/config/nicertoffice/config/system.performance.yml, project/config/nicybersecuritycentre/config/system.performance.yml, project/config/nijac/config/system.performance.yml, project/config/ppsni/config/system.performance.yml, project/config/publicappointmentsni/config/system.performance.yml, project/config/sentencereview/config/system.performance.yml, project/config/victimspaymentsboard/config/system.performance.yml
Turn off js aggregation in order to avoid moderation sidebar problems under core 10.3
=> Turn off js aggregation 

composer.lock
Upgrade origins modules and unity modules
=> Unity 2 release

composer.lock
This core upgrade is being applied as a hotfix to production
=> Drupal core upgrade 10.3.13
